/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package deviceregisster;
import java.util.*;
import java.io.*;
import java.sql.*;
import javax.swing.*;
import deviceregister.User;

/**
*
* @author elna.vanaarde
*/
public class FrmLogin extends javax.swing.JFrame
{
 //Create object of the UserArray class
 private UserArray users = new UserArray();
 public FrmLogin()
 {
 initComponents();
 }
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {
 THE CODE IN THIS METHOD IS GENERATED BY THE FORM EDITOR. I’VE REMOVED IT TO AVOID CONFUSION.
 }// </editor-fold>//GEN-END:initComponents
 private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {
 if (txtUserName.getText().equals(""))
 //Alternative: if (txtUserName.getText().isEmpty())
 {
 //Ask user to supply value
 JOptionPane.showMessageDialog(this, "Please type in a username");
 }
 else if (pwfPassword.getPassword().length == 0) //Validate if password is filled in
 {
 //Ask user to supply value
 JOptionPane.showMessageDialog(this, "Please type in a password");
 }
 else if (!users.userExists(txtUserName.getText())) //Check if username exists
 {
 JOptionPane.showMessageDialog(this,
 "User name does not exist.");
 }
 else if (!users.passwordValid(txtUserName.getText(), pwfPassword))
 //Check if password is correct))
 {
 JOptionPane.showMessageDialog(this, "Incorrect password for this user.");
 }
 else //All details filled in and correct
 {
 //new FrmMainTEMP().setVisible(true);
 new FrmMain().setVisible(true);
 this.dispose();
 }
 }//GEN-LAST:event_btnLogInActionPerformed
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
 }
}