/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetickets;

import java.time.*;
import java.util.Date;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SD10015565
 */
public class ticketRegister extends javax.swing.JFrame {

    /**
     * Creates new form ticketRegister
     */
    public ticketRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        pnlFields = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        cbxChooseTo = new javax.swing.JComboBox<>();
        cbxChooseFrom = new javax.swing.JComboBox<>();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        lblNumOfTickets = new javax.swing.JLabel();
        txtNumberOfTickets = new javax.swing.JTextField();
        lblTimeslot = new javax.swing.JLabel();
        cbxTimeslot = new javax.swing.JComboBox<>();
        rbnYes = new javax.swing.JRadioButton();
        lblMembership = new javax.swing.JLabel();
        rbnNo = new javax.swing.JRadioButton();
        btnBook = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnlError = new javax.swing.JPanel();
        lblIsFn = new javax.swing.JLabel();
        lblIsLn = new javax.swing.JLabel();
        lblIsDes = new javax.swing.JLabel();
        lblIsDte = new javax.swing.JLabel();
        lblIsMbr = new javax.swing.JLabel();
        lblIsNrTckt = new javax.swing.JLabel();
        lblIsTime = new javax.swing.JLabel();
        lblIsFrom = new javax.swing.JLabel();
        lblIsTo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegister.setText("Ticket Registration");
        pnlFields.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        cbxChooseTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "Pretoria", "Durban", "Bloemfontein", "Cape Town" }));
        cbxChooseTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChooseToActionPerformed(evt);
            }
        });
        pnlFields.add(cbxChooseTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 217, -1, -1));

        cbxChooseFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "Pretoria", "Durban", "Bloemfontein", "Cape Town" }));
        pnlFields.add(cbxChooseFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 179, -1, -1));

        lblFirstname.setText("First Name:");
        pnlFields.add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));
        pnlFields.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 125, -1));

        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });
        pnlFields.add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 125, -1));

        lblLastname.setText("Last Name:");
        pnlFields.add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        lblDestination.setText("Destination:");
        pnlFields.add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        lblFrom.setText("From");
        pnlFields.add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));

        lblTo.setText("To");
        pnlFields.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lblNumOfTickets.setText("Number Of Tickets:");
        pnlFields.add(lblNumOfTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, -1, -1));

        txtNumberOfTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfTicketsActionPerformed(evt);
            }
        });
        pnlFields.add(txtNumberOfTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 424, 125, -1));

        lblTimeslot.setText("Time Slot");
        pnlFields.add(lblTimeslot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        cbxTimeslot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "11:00", "12:30", "14:00", "15:30", "18:00", "19:30", "21:00", " " }));
        pnlFields.add(cbxTimeslot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, -1));

        btnGroup.add(rbnYes);
        rbnYes.setText("Yes");
        pnlFields.add(rbnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 358, -1, -1));

        lblMembership.setText("Membership");
        pnlFields.add(lblMembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, -1, -1));

        btnGroup.add(rbnNo);
        rbnNo.setText("No");
        rbnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnNoActionPerformed(evt);
            }
        });
        pnlFields.add(rbnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 358, -1, -1));

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        pnlFields.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 462, 87, -1));

        lblDate.setText("Date of flight:");
        pnlFields.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 301, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 2", "Item 3", "Item 4" }));
        pnlFields.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 300, 80, -1));

        pnlError.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlError.add(lblIsFn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        pnlError.add(lblIsLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        pnlError.add(lblIsDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 0, 10));
        pnlError.add(lblIsDte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        pnlError.add(lblIsMbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        pnlError.add(lblIsNrTckt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));
        pnlError.add(lblIsTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        pnlError.add(lblIsFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        pnlError.add(lblIsTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlError, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(pnlError, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtNumberOfTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfTicketsActionPerformed

    private void cbxChooseToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChooseToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxChooseToActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        lblIsDes.setText("");
        lblIsDte.setText("");
        lblIsFn.setText("");
        lblIsLn.setText("");
        lblIsMbr.setText("");
        lblIsNrTckt.setText("");
        lblIsTime.setText("");
        lblIsTo.setText("");
        lblIsFrom.setText("");
        
        ButtonModel bm = null;
        String error = "has not been supplied";
        String needFirstname, needLastname, needNumberOfTickets, needMembership, needDestination, NOTS = txtNumberOfTickets.getText();
        
        if (cbxChooseFrom.getSelectedIndex() == cbxChooseTo.getSelectedIndex() && cbxChooseFrom.getSelectedIndex() != 0 && cbxChooseTo.getSelectedIndex() != 0) {
            lblIsDes.setText("the destination cannot be the starting point");
        }
        if (txtNumberOfTickets.getText().isEmpty()) {
            lblIsNrTckt.setText("a possible amount of Tickets " + error);
        }else{
            try{
                int NOTickets = Integer.parseInt(txtNumberOfTickets.getText());
                if (NOTickets<=0) {
                    lblIsNrTckt.setText("a possible amount of Tickets " + error);
                }
            }catch(NumberFormatException e){
                lblIsNrTckt.setText("a possible amount of Tickets " + error);
            }
        }
        if (cbxChooseTo.getSelectedIndex() == 0) {
            lblIsTo.setText("starting city not selected");
        }
        if (cbxChooseFrom.getSelectedIndex() == 0) {
            lblIsFrom.setText("Destination not selected");
        }
        if (cbxTimeslot.getSelectedIndex() == 0) {
            lblIsTime.setText("A time has not been selected");
        }
        if (txtFirstname.getText().isEmpty() || txtLastname.getText().isEmpty()) {
            lblIsFn.setText("Firstname " + error);
        }
        if (txtLastname.getText().isEmpty()) {
            lblIsLn.setText("Firstname " + error);
        }
        if (btnGroup.isSelected(bm)) {
            lblIsMbr.setText("The membership status " + error);
        }
        if (jdpFlight.getDate() == null) {
            lblIsDte.setText("Flight booking date " + error);
        }else{
            LocalDate flightDay = jdpFlight.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate currentDate = LocalDate.now();
            if(flightDay == currentDate || flightDay.isBefore(currentDate)){
                lblIsDte.setText("Flight booking cannot be same day or before current date");
            }
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void rbnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnNoActionPerformed

    private void jdpFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpFlightActionPerformed
        
    }//GEN-LAST:event_jdpFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JComboBox<String> cbxChooseFrom;
    private javax.swing.JComboBox<String> cbxChooseTo;
    private javax.swing.JComboBox<String> cbxTimeslot;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblIsDes;
    private javax.swing.JLabel lblIsDte;
    private javax.swing.JLabel lblIsFn;
    private javax.swing.JLabel lblIsFrom;
    private javax.swing.JLabel lblIsLn;
    private javax.swing.JLabel lblIsMbr;
    private javax.swing.JLabel lblIsNrTckt;
    private javax.swing.JLabel lblIsTime;
    private javax.swing.JLabel lblIsTo;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMembership;
    private javax.swing.JLabel lblNumOfTickets;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTimeslot;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnlError;
    private javax.swing.JPanel pnlFields;
    private javax.swing.JRadioButton rbnNo;
    private javax.swing.JRadioButton rbnYes;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtNumberOfTickets;
    // End of variables declaration//GEN-END:variables
}
